<#
  Creates website\api\config.local.php on YOUR computer with your Network Solutions
  database details, email settings and admin password. The file is git-ignored, so
  it is never pushed to GitHub. Passwords are typed into this window only.

  Run (PowerShell, from this folder):   .\configure-site.ps1
  Use SQLite instead of MySQL:          .\configure-site.ps1 -UseSqlite

  Then run .\build-for-hosting.ps1 and upload the result (see README.txt).
#>
param(
  [string]$DbHost,
  [string]$DbName,
  [string]$DbUser,
  [string]$NotifyEmail,
  [string]$MailFrom,
  [switch]$UseSqlite,
  [switch]$Force
)

$ErrorActionPreference = 'Stop'
$cfgPath = Join-Path $PSScriptRoot 'website\api\config.local.php'

function Ask($label, $default) {
  $prompt = if ($default) { "$label [$default]" } else { $label }
  $v = Read-Host $prompt
  if ([string]::IsNullOrWhiteSpace($v)) { $default } else { $v.Trim() }
}
function Plain([securestring]$s) {
  $b = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($s)
  try { [Runtime.InteropServices.Marshal]::PtrToStringBSTR($b) } finally { [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($b) }
}
function Secret($label, $envName) {
  $fromEnv = [Environment]::GetEnvironmentVariable($envName)
  if ($fromEnv) { return $fromEnv }
  Plain (Read-Host $label -AsSecureString)
}
# Quote a value as a PHP single-quoted string.
function Q($s) { "'" + $s.Replace('\', '\\').Replace("'", "\'") + "'" }

if ((Test-Path $cfgPath) -and -not $Force) {
  $a = Read-Host 'api\config.local.php already exists. Overwrite it? (y/N)'
  if ($a -notmatch '^[yY]') { Write-Host 'Nothing changed.'; return }
}

Write-Host ''
Write-Host 'Network Solutions > Websites & Hosting > Manage > Database Manager / MySQL Management'
Write-Host 'shows the database details you need below.'
Write-Host ''

$db = ''
if (-not $UseSqlite) {
  if (-not $DbHost) { $DbHost = Ask 'Database host (Network Solutions normally uses localhost)' 'localhost' }
  if (-not $DbName) { $DbName = Ask 'Database name' '' }
  if (-not $DbUser) { $DbUser = Ask 'Database user' '' }
  $dbPass = Secret 'Database password (hidden)' 'COC_DB_PASS'
  if (-not $DbName -or -not $DbUser -or -not $dbPass) { throw 'Database name, user and password are required (or re-run with -UseSqlite).' }
  $db = @"
    'db' => [
        'driver'     => 'mysql',
        'mysql_host' => $(Q $DbHost),
        'mysql_port' => 3306,
        'mysql_name' => $(Q $DbName),
        'mysql_user' => $(Q $DbUser),
        'mysql_pass' => $(Q $dbPass),
    ],

"@
}

if (-not $NotifyEmail) { $NotifyEmail = Ask 'Email address that should receive new-submission alerts' '' }
if (-not $MailFrom) {
  $dom = if ($NotifyEmail -match '@(.+)$') { $Matches[1] } else { '' }
  $MailFrom = Ask 'Sender address for those emails (use one on your own domain)' $(if ($dom) { "no-reply@$dom" } else { '' })
}

# Admin password -> bcrypt hash (needs PHP on this computer, e.g. XAMPP's).
$php = $null
$cmd = Get-Command php -ErrorAction SilentlyContinue
if ($cmd) { $php = $cmd.Source } elseif (Test-Path 'C:\xampp\php\php.exe') { $php = 'C:\xampp\php\php.exe' }
$hash = ''
if ($php) {
  $pw = Secret 'Choose an admin password for /admin/ (10+ characters, hidden)' 'COC_ADMIN_PASS'
  if ($pw.Length -lt 10) { throw 'The admin password must be at least 10 characters.' }
  $env:COC_TMP_PW = $pw
  try { $hash = (& $php -r "echo password_hash(getenv('COC_TMP_PW'), PASSWORD_DEFAULT);").Trim() } finally { Remove-Item Env:COC_TMP_PW -ErrorAction SilentlyContinue }
  if ($hash -notmatch '^\$2y\$') { throw 'Could not create the password hash.' }
} else {
  Write-Host 'PHP was not found on this computer, so the admin password step is skipped.'
  Write-Host 'After uploading, open https://yourdomain/admin/ once - it will create the line to add.'
}

$body = @"
<?php
// Generated by configure-site.ps1. Private: never commit or share this file.
return [
$db    'notify_email' => $(Q $NotifyEmail),
    'mail_from'    => $(Q $MailFrom),
    'admin_password_hash' => $(Q $hash),
];

"@
[System.IO.File]::WriteAllText($cfgPath, $body, (New-Object System.Text.UTF8Encoding($false)))

Write-Host ''
Write-Host "Saved $cfgPath"
Write-Host 'Next: double-click 2-build-upload-file.bat (or run .\build-for-hosting.ps1).'
Write-Host 'Keep dist\ and coc-website-upload.zip private: they now contain your database password.'
